### ISSUE TITLE
descriere detaliata

### ISSUE THREAD

**Issue by AlucardMode0** [PddTV/AMD_TheShop#1]
Ar fi ok daca ai pune o descriere mai detaliata a ce ai lucrat . adica : azi am facut :
APU -> functia 1 
       -> functia 2
        -> am rezolvat problema asta din constructor 

USER -> am facut logarea 
          -> am verificat logarea

**Comment by PddTV** [comment]
Problema rezolvata prin adaugarea fisierului [README.md](https://github.com/PddTV/AMD_TheShop#readme)
